# fly.toml app configuration file generated for turso-drizzle-bun on 2024-04-01T14:28:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bun-drizzle-turso'
primary_region = 'yyz'

[build]

[deploy]
  release_command = "bun run db:migrate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
